source 'https://cdn.cocoapods.org'
platform :ios, '14.0'
use_frameworks!

target 'iosApp' do
  # Point at the Gradle‑generated podspec directory
# pod 'shared', :path => '../shared' # ✅ Correct in Kotlin 2.0
  pod 'shared', path: '../shared/build/cocoapods'
  pod 'GoogleSignIn'
end
